apiVersion: remediation.medik8s.io/v1alpha1
kind: NodeHealthCheck
metadata:
  name: master-availability
spec:
  maxUnhealthy: 1
  remediationTemplate:
    apiVersion: fence-agents-remediation.medik8s.io/v1alpha1
    kind: FenceAgentsRemediationTemplate
    name: far-idrac-template
    namespace: openshift-workload-availability
  selector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: Exists
  unhealthyConditions:
    - type: Ready
      status: "False"
      duration: 1s
    - type: Ready
      status: Unknown
      duration: 1s
